//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from NinjaVars.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


    

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="NinjaVarsParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface INinjaVarsListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] NinjaVarsParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] NinjaVarsParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] NinjaVarsParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] NinjaVarsParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.intOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntOperand([NotNull] NinjaVarsParser.IntOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.intOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntOperand([NotNull] NinjaVarsParser.IntOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.intTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntTerm([NotNull] NinjaVarsParser.IntTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.intTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntTerm([NotNull] NinjaVarsParser.IntTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.intExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntExpr([NotNull] NinjaVarsParser.IntExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.intExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntExpr([NotNull] NinjaVarsParser.IntExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.intExprEx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntExprEx([NotNull] NinjaVarsParser.IntExprExContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.intExprEx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntExprEx([NotNull] NinjaVarsParser.IntExprExContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.doubleOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleOperand([NotNull] NinjaVarsParser.DoubleOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.doubleOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleOperand([NotNull] NinjaVarsParser.DoubleOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.doubleTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleTerm([NotNull] NinjaVarsParser.DoubleTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.doubleTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleTerm([NotNull] NinjaVarsParser.DoubleTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.doubleExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleExpr([NotNull] NinjaVarsParser.DoubleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.doubleExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleExpr([NotNull] NinjaVarsParser.DoubleExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.doubleExprEx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleExprEx([NotNull] NinjaVarsParser.DoubleExprExContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.doubleExprEx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleExprEx([NotNull] NinjaVarsParser.DoubleExprExContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.boolOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolOperand([NotNull] NinjaVarsParser.BoolOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.boolOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolOperand([NotNull] NinjaVarsParser.BoolOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.boolExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolExpr([NotNull] NinjaVarsParser.BoolExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.boolExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolExpr([NotNull] NinjaVarsParser.BoolExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.boolExprEx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolExprEx([NotNull] NinjaVarsParser.BoolExprExContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.boolExprEx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolExprEx([NotNull] NinjaVarsParser.BoolExprExContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare([NotNull] NinjaVarsParser.DeclareContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare([NotNull] NinjaVarsParser.DeclareContext context);
}
