//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from NinjaVars.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="NinjaVarsParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface INinjaVarsListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] NinjaVarsParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] NinjaVarsParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMain([NotNull] NinjaVarsParser.MainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMain([NotNull] NinjaVarsParser.MainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.main_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMain_signature([NotNull] NinjaVarsParser.Main_signatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.main_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMain_signature([NotNull] NinjaVarsParser.Main_signatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] NinjaVarsParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] NinjaVarsParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.v_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterV_function([NotNull] NinjaVarsParser.V_functionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.v_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitV_function([NotNull] NinjaVarsParser.V_functionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.v_fun_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterV_fun_signature([NotNull] NinjaVarsParser.V_fun_signatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.v_fun_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitV_fun_signature([NotNull] NinjaVarsParser.V_fun_signatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.m_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterM_function([NotNull] NinjaVarsParser.M_functionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.m_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitM_function([NotNull] NinjaVarsParser.M_functionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.m_fun_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterM_fun_signature([NotNull] NinjaVarsParser.M_fun_signatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.m_fun_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitM_fun_signature([NotNull] NinjaVarsParser.M_fun_signatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCode([NotNull] NinjaVarsParser.CodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCode([NotNull] NinjaVarsParser.CodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.main_code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMain_code([NotNull] NinjaVarsParser.Main_codeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.main_code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMain_code([NotNull] NinjaVarsParser.Main_codeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] NinjaVarsParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] NinjaVarsParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.method_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_return([NotNull] NinjaVarsParser.Method_returnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.method_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_return([NotNull] NinjaVarsParser.Method_returnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParams([NotNull] NinjaVarsParser.ParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParams([NotNull] NinjaVarsParser.ParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.var_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_signature([NotNull] NinjaVarsParser.Var_signatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.var_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_signature([NotNull] NinjaVarsParser.Var_signatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.builtin_func_p"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuiltin_func_p([NotNull] NinjaVarsParser.Builtin_func_pContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.builtin_func_p"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuiltin_func_p([NotNull] NinjaVarsParser.Builtin_func_pContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.builtin_func_e"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuiltin_func_e([NotNull] NinjaVarsParser.Builtin_func_eContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.builtin_func_e"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuiltin_func_e([NotNull] NinjaVarsParser.Builtin_func_eContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] NinjaVarsParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] NinjaVarsParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.parameterized_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterized_call([NotNull] NinjaVarsParser.Parameterized_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.parameterized_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterized_call([NotNull] NinjaVarsParser.Parameterized_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.simple_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_call([NotNull] NinjaVarsParser.Simple_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.simple_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_call([NotNull] NinjaVarsParser.Simple_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.custom_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustom_call([NotNull] NinjaVarsParser.Custom_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.custom_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustom_call([NotNull] NinjaVarsParser.Custom_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.call_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_params([NotNull] NinjaVarsParser.Call_paramsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.call_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_params([NotNull] NinjaVarsParser.Call_paramsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.val_or_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVal_or_id([NotNull] NinjaVarsParser.Val_or_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.val_or_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVal_or_id([NotNull] NinjaVarsParser.Val_or_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.ariphOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAriphOperand([NotNull] NinjaVarsParser.AriphOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.ariphOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAriphOperand([NotNull] NinjaVarsParser.AriphOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.ariphTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAriphTerm([NotNull] NinjaVarsParser.AriphTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.ariphTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAriphTerm([NotNull] NinjaVarsParser.AriphTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.ariphExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAriphExpr([NotNull] NinjaVarsParser.AriphExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.ariphExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAriphExpr([NotNull] NinjaVarsParser.AriphExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.ariphExprEx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAriphExprEx([NotNull] NinjaVarsParser.AriphExprExContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.ariphExprEx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAriphExprEx([NotNull] NinjaVarsParser.AriphExprExContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.boolOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolOperand([NotNull] NinjaVarsParser.BoolOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.boolOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolOperand([NotNull] NinjaVarsParser.BoolOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.boolExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolExpr([NotNull] NinjaVarsParser.BoolExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.boolExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolExpr([NotNull] NinjaVarsParser.BoolExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.boolExprEx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolExprEx([NotNull] NinjaVarsParser.BoolExprExContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.boolExprEx"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolExprEx([NotNull] NinjaVarsParser.BoolExprExContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare([NotNull] NinjaVarsParser.DeclareContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare([NotNull] NinjaVarsParser.DeclareContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.sin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSin([NotNull] NinjaVarsParser.SinContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.sin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSin([NotNull] NinjaVarsParser.SinContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.cos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCos([NotNull] NinjaVarsParser.CosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.cos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCos([NotNull] NinjaVarsParser.CosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.tan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTan([NotNull] NinjaVarsParser.TanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.tan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTan([NotNull] NinjaVarsParser.TanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.asin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsin([NotNull] NinjaVarsParser.AsinContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.asin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsin([NotNull] NinjaVarsParser.AsinContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.acos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAcos([NotNull] NinjaVarsParser.AcosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.acos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAcos([NotNull] NinjaVarsParser.AcosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.atan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtan([NotNull] NinjaVarsParser.AtanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.atan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtan([NotNull] NinjaVarsParser.AtanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.atan2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtan2([NotNull] NinjaVarsParser.Atan2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.atan2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtan2([NotNull] NinjaVarsParser.Atan2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.myif"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMyif([NotNull] NinjaVarsParser.MyifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.myif"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMyif([NotNull] NinjaVarsParser.MyifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.myif_short"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMyif_short([NotNull] NinjaVarsParser.Myif_shortContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.myif_short"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMyif_short([NotNull] NinjaVarsParser.Myif_shortContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.mywhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMywhile([NotNull] NinjaVarsParser.MywhileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.mywhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMywhile([NotNull] NinjaVarsParser.MywhileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.mydo_while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMydo_while([NotNull] NinjaVarsParser.Mydo_whileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.mydo_while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMydo_while([NotNull] NinjaVarsParser.Mydo_whileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.myfor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMyfor([NotNull] NinjaVarsParser.MyforContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.myfor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMyfor([NotNull] NinjaVarsParser.MyforContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.meaningfulType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeaningfulType([NotNull] NinjaVarsParser.MeaningfulTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.meaningfulType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeaningfulType([NotNull] NinjaVarsParser.MeaningfulTypeContext context);
}
