//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from NinjaVars.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class NinjaVarsLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OPSEP=1, INTKEY=2, DOUBLEKEY=3, BOOLKEY=4, ASSIGN=5, ADD=6, SUB=7, MUL=8, 
		DIV=9, ADDASSIGN=10, SUBASSIGN=11, MULASSIGN=12, DIVASSIGN=13, AND=14, 
		OR=15, LESS=16, GREATER=17, EQUAL=18, NOTEQUAL=19, LESSEQUAL=20, GREQUAL=21, 
		LPAREN=22, RPAREN=23, WS=24, BOOL=25, DOUBLE=26, INT=27, ID=28;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"OPSEP", "INTKEY", "DOUBLEKEY", "BOOLKEY", "ASSIGN", "ADD", "SUB", "MUL", 
		"DIV", "ADDASSIGN", "SUBASSIGN", "MULASSIGN", "DIVASSIGN", "AND", "OR", 
		"LESS", "GREATER", "EQUAL", "NOTEQUAL", "LESSEQUAL", "GREQUAL", "LPAREN", 
		"RPAREN", "WS", "BOOL", "DOUBLE", "INT", "ID", "LETTER", "DIGIT"
	};


	public NinjaVarsLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public NinjaVarsLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'\n'", "'int'", "'double'", "'bool'", "'='", "'+'", "'-'", "'*'", 
		"'/'", "'+='", "'-='", "'*='", "'/='", "'&&'", "'||'", "'<'", "'>'", "'=='", 
		"'!='", "'<='", "'>='", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OPSEP", "INTKEY", "DOUBLEKEY", "BOOLKEY", "ASSIGN", "ADD", "SUB", 
		"MUL", "DIV", "ADDASSIGN", "SUBASSIGN", "MULASSIGN", "DIVASSIGN", "AND", 
		"OR", "LESS", "GREATER", "EQUAL", "NOTEQUAL", "LESSEQUAL", "GREQUAL", 
		"LPAREN", "RPAREN", "WS", "BOOL", "DOUBLE", "INT", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "NinjaVars.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static NinjaVarsLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1E', '\xB6', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', 
		'\x6', '\x19', '\x83', '\n', '\x19', '\r', '\x19', '\xE', '\x19', '\x84', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x5', '\x1A', '\x92', '\n', '\x1A', '\x3', '\x1B', '\x5', 
		'\x1B', '\x95', '\n', '\x1B', '\x3', '\x1B', '\a', '\x1B', '\x98', '\n', 
		'\x1B', '\f', '\x1B', '\xE', '\x1B', '\x9B', '\v', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1B', '\x6', '\x1B', '\x9F', '\n', '\x1B', '\r', '\x1B', '\xE', 
		'\x1B', '\xA0', '\x3', '\x1C', '\x5', '\x1C', '\xA4', '\n', '\x1C', '\x3', 
		'\x1C', '\x6', '\x1C', '\xA7', '\n', '\x1C', '\r', '\x1C', '\xE', '\x1C', 
		'\xA8', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\a', '\x1D', '\xAE', 
		'\n', '\x1D', '\f', '\x1D', '\xE', '\x1D', '\xB1', '\v', '\x1D', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x2', '\x2', ' ', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', 
		'\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', 
		'#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', 
		'\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', 
		'\x1D', '\x39', '\x1E', ';', '\x2', '=', '\x2', '\x3', '\x2', '\a', '\x5', 
		'\x2', '\v', '\v', '\xF', '\xF', '\"', '\"', '\x4', '\x2', '-', '-', '/', 
		'/', '\x3', '\x2', '.', '.', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x3', '\x2', '\x32', ';', '\x2', '\xBC', '\x2', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x3', '?', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '\x41', '\x3', '\x2', '\x2', '\x2', '\a', 
		'\x45', '\x3', '\x2', '\x2', '\x2', '\t', 'L', '\x3', '\x2', '\x2', '\x2', 
		'\v', 'Q', '\x3', '\x2', '\x2', '\x2', '\r', 'S', '\x3', '\x2', '\x2', 
		'\x2', '\xF', 'U', '\x3', '\x2', '\x2', '\x2', '\x11', 'W', '\x3', '\x2', 
		'\x2', '\x2', '\x13', 'Y', '\x3', '\x2', '\x2', '\x2', '\x15', '[', '\x3', 
		'\x2', '\x2', '\x2', '\x17', '^', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'\x61', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', 'g', '\x3', '\x2', '\x2', '\x2', '\x1F', 'j', '\x3', '\x2', 
		'\x2', '\x2', '!', 'm', '\x3', '\x2', '\x2', '\x2', '#', 'o', '\x3', '\x2', 
		'\x2', '\x2', '%', 'q', '\x3', '\x2', '\x2', '\x2', '\'', 't', '\x3', 
		'\x2', '\x2', '\x2', ')', 'w', '\x3', '\x2', '\x2', '\x2', '+', 'z', '\x3', 
		'\x2', '\x2', '\x2', '-', '}', '\x3', '\x2', '\x2', '\x2', '/', '\x7F', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\x82', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\x91', '\x3', '\x2', '\x2', '\x2', '\x35', '\x94', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\xA3', '\x3', '\x2', '\x2', '\x2', '\x39', '\xAA', 
		'\x3', '\x2', '\x2', '\x2', ';', '\xB2', '\x3', '\x2', '\x2', '\x2', '=', 
		'\xB4', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', '\f', '\x2', '\x2', 
		'@', '\x4', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', 'k', '\x2', 
		'\x2', '\x42', '\x43', '\a', 'p', '\x2', '\x2', '\x43', '\x44', '\a', 
		'v', '\x2', '\x2', '\x44', '\x6', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x46', '\a', '\x66', '\x2', '\x2', '\x46', 'G', '\a', 'q', '\x2', '\x2', 
		'G', 'H', '\a', 'w', '\x2', '\x2', 'H', 'I', '\a', '\x64', '\x2', '\x2', 
		'I', 'J', '\a', 'n', '\x2', '\x2', 'J', 'K', '\a', 'g', '\x2', '\x2', 
		'K', '\b', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\a', '\x64', '\x2', 
		'\x2', 'M', 'N', '\a', 'q', '\x2', '\x2', 'N', 'O', '\a', 'q', '\x2', 
		'\x2', 'O', 'P', '\a', 'n', '\x2', '\x2', 'P', '\n', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'R', '\a', '?', '\x2', '\x2', 'R', '\f', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\a', '-', '\x2', '\x2', 'T', '\xE', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\a', '/', '\x2', '\x2', 'V', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'X', '\a', ',', '\x2', '\x2', 'X', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'Z', '\a', '\x31', '\x2', '\x2', 'Z', '\x14', '\x3', '\x2', 
		'\x2', '\x2', '[', '\\', '\a', '-', '\x2', '\x2', '\\', ']', '\a', '?', 
		'\x2', '\x2', ']', '\x16', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', 
		'/', '\x2', '\x2', '_', '`', '\a', '?', '\x2', '\x2', '`', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '\x62', '\a', ',', '\x2', '\x2', '\x62', 
		'\x63', '\a', '?', '\x2', '\x2', '\x63', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\x65', '\a', '\x31', '\x2', '\x2', '\x65', '\x66', '\a', 
		'?', '\x2', '\x2', '\x66', '\x1C', '\x3', '\x2', '\x2', '\x2', 'g', 'h', 
		'\a', '(', '\x2', '\x2', 'h', 'i', '\a', '(', '\x2', '\x2', 'i', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', '~', '\x2', '\x2', 'k', 'l', 
		'\a', '~', '\x2', '\x2', 'l', ' ', '\x3', '\x2', '\x2', '\x2', 'm', 'n', 
		'\a', '>', '\x2', '\x2', 'n', '\"', '\x3', '\x2', '\x2', '\x2', 'o', 'p', 
		'\a', '@', '\x2', '\x2', 'p', '$', '\x3', '\x2', '\x2', '\x2', 'q', 'r', 
		'\a', '?', '\x2', '\x2', 'r', 's', '\a', '?', '\x2', '\x2', 's', '&', 
		'\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', '#', '\x2', '\x2', 'u', 'v', 
		'\a', '?', '\x2', '\x2', 'v', '(', '\x3', '\x2', '\x2', '\x2', 'w', 'x', 
		'\a', '>', '\x2', '\x2', 'x', 'y', '\a', '?', '\x2', '\x2', 'y', '*', 
		'\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', '@', '\x2', '\x2', '{', '|', 
		'\a', '?', '\x2', '\x2', '|', ',', '\x3', '\x2', '\x2', '\x2', '}', '~', 
		'\a', '*', '\x2', '\x2', '~', '.', '\x3', '\x2', '\x2', '\x2', '\x7F', 
		'\x80', '\a', '+', '\x2', '\x2', '\x80', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x83', '\t', '\x2', '\x2', '\x2', '\x82', '\x81', '\x3', 
		'\x2', '\x2', '\x2', '\x83', '\x84', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\x86', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\b', 
		'\x19', '\x2', '\x2', '\x87', '\x32', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x89', '\a', 'v', '\x2', '\x2', '\x89', '\x8A', '\a', 't', '\x2', '\x2', 
		'\x8A', '\x8B', '\a', 'w', '\x2', '\x2', '\x8B', '\x92', '\a', 'g', '\x2', 
		'\x2', '\x8C', '\x8D', '\a', 'h', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'\x63', '\x2', '\x2', '\x8E', '\x8F', '\a', 'n', '\x2', '\x2', '\x8F', 
		'\x90', '\a', 'u', '\x2', '\x2', '\x90', '\x92', '\a', 'g', '\x2', '\x2', 
		'\x91', '\x88', '\x3', '\x2', '\x2', '\x2', '\x91', '\x8C', '\x3', '\x2', 
		'\x2', '\x2', '\x92', '\x34', '\x3', '\x2', '\x2', '\x2', '\x93', '\x95', 
		'\t', '\x3', '\x2', '\x2', '\x94', '\x93', '\x3', '\x2', '\x2', '\x2', 
		'\x94', '\x95', '\x3', '\x2', '\x2', '\x2', '\x95', '\x99', '\x3', '\x2', 
		'\x2', '\x2', '\x96', '\x98', '\x5', '=', '\x1F', '\x2', '\x97', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\x98', '\x9B', '\x3', '\x2', '\x2', '\x2', 
		'\x99', '\x97', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\x3', '\x2', 
		'\x2', '\x2', '\x9A', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x99', 
		'\x3', '\x2', '\x2', '\x2', '\x9C', '\x9E', '\t', '\x4', '\x2', '\x2', 
		'\x9D', '\x9F', '\x5', '=', '\x1F', '\x2', '\x9E', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '\x9F', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x9E', 
		'\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\x3', '\x2', '\x2', '\x2', 
		'\xA1', '\x36', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA4', '\t', '\x3', 
		'\x2', '\x2', '\xA3', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', 
		'\x3', '\x2', '\x2', '\x2', '\xA4', '\xA6', '\x3', '\x2', '\x2', '\x2', 
		'\xA5', '\xA7', '\x5', '=', '\x1F', '\x2', '\xA6', '\xA5', '\x3', '\x2', 
		'\x2', '\x2', '\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA6', 
		'\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', '\x2', 
		'\xA9', '\x38', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAF', '\x5', ';', 
		'\x1E', '\x2', '\xAB', '\xAE', '\x5', ';', '\x1E', '\x2', '\xAC', '\xAE', 
		'\x5', '=', '\x1F', '\x2', '\xAD', '\xAB', '\x3', '\x2', '\x2', '\x2', 
		'\xAD', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xB1', '\x3', '\x2', 
		'\x2', '\x2', '\xAF', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB0', 
		'\x3', '\x2', '\x2', '\x2', '\xB0', ':', '\x3', '\x2', '\x2', '\x2', '\xB1', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\t', '\x5', '\x2', 
		'\x2', '\xB3', '<', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\t', 
		'\x6', '\x2', '\x2', '\xB5', '>', '\x3', '\x2', '\x2', '\x2', '\f', '\x2', 
		'\x84', '\x91', '\x94', '\x99', '\xA0', '\xA3', '\xA8', '\xAD', '\xAF', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
