//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from NinjaVars.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="INinjaVarsListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class NinjaVarsBaseListener : INinjaVarsListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] NinjaVarsParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] NinjaVarsParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain([NotNull] NinjaVarsParser.MainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain([NotNull] NinjaVarsParser.MainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.main_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain_signature([NotNull] NinjaVarsParser.Main_signatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.main_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain_signature([NotNull] NinjaVarsParser.Main_signatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] NinjaVarsParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] NinjaVarsParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.v_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterV_function([NotNull] NinjaVarsParser.V_functionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.v_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitV_function([NotNull] NinjaVarsParser.V_functionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.v_fun_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterV_fun_signature([NotNull] NinjaVarsParser.V_fun_signatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.v_fun_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitV_fun_signature([NotNull] NinjaVarsParser.V_fun_signatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.m_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterM_function([NotNull] NinjaVarsParser.M_functionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.m_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitM_function([NotNull] NinjaVarsParser.M_functionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.m_fun_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterM_fun_signature([NotNull] NinjaVarsParser.M_fun_signatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.m_fun_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitM_fun_signature([NotNull] NinjaVarsParser.M_fun_signatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode([NotNull] NinjaVarsParser.CodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode([NotNull] NinjaVarsParser.CodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.main_code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain_code([NotNull] NinjaVarsParser.Main_codeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.main_code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain_code([NotNull] NinjaVarsParser.Main_codeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperation([NotNull] NinjaVarsParser.OperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperation([NotNull] NinjaVarsParser.OperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.method_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_return([NotNull] NinjaVarsParser.Method_returnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.method_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_return([NotNull] NinjaVarsParser.Method_returnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams([NotNull] NinjaVarsParser.ParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams([NotNull] NinjaVarsParser.ParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.var_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_signature([NotNull] NinjaVarsParser.Var_signatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.var_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_signature([NotNull] NinjaVarsParser.Var_signatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.builtin_func_p"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuiltin_func_p([NotNull] NinjaVarsParser.Builtin_func_pContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.builtin_func_p"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuiltin_func_p([NotNull] NinjaVarsParser.Builtin_func_pContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.builtin_func_e"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuiltin_func_e([NotNull] NinjaVarsParser.Builtin_func_eContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.builtin_func_e"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuiltin_func_e([NotNull] NinjaVarsParser.Builtin_func_eContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] NinjaVarsParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] NinjaVarsParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.parameterized_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterized_call([NotNull] NinjaVarsParser.Parameterized_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.parameterized_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterized_call([NotNull] NinjaVarsParser.Parameterized_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.simple_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_call([NotNull] NinjaVarsParser.Simple_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.simple_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_call([NotNull] NinjaVarsParser.Simple_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.custom_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCustom_call([NotNull] NinjaVarsParser.Custom_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.custom_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCustom_call([NotNull] NinjaVarsParser.Custom_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.call_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_params([NotNull] NinjaVarsParser.Call_paramsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.call_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_params([NotNull] NinjaVarsParser.Call_paramsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.val_or_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVal_or_id([NotNull] NinjaVarsParser.Val_or_idContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.val_or_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVal_or_id([NotNull] NinjaVarsParser.Val_or_idContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.ariphOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAriphOperand([NotNull] NinjaVarsParser.AriphOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.ariphOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAriphOperand([NotNull] NinjaVarsParser.AriphOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.ariphTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAriphTerm([NotNull] NinjaVarsParser.AriphTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.ariphTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAriphTerm([NotNull] NinjaVarsParser.AriphTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.ariphExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAriphExpr([NotNull] NinjaVarsParser.AriphExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.ariphExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAriphExpr([NotNull] NinjaVarsParser.AriphExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.ariphExprEx"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAriphExprEx([NotNull] NinjaVarsParser.AriphExprExContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.ariphExprEx"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAriphExprEx([NotNull] NinjaVarsParser.AriphExprExContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.boolOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolOperand([NotNull] NinjaVarsParser.BoolOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.boolOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolOperand([NotNull] NinjaVarsParser.BoolOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.boolExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolExpr([NotNull] NinjaVarsParser.BoolExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.boolExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolExpr([NotNull] NinjaVarsParser.BoolExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.boolExprEx"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolExprEx([NotNull] NinjaVarsParser.BoolExprExContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.boolExprEx"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolExprEx([NotNull] NinjaVarsParser.BoolExprExContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.declare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclare([NotNull] NinjaVarsParser.DeclareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.declare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclare([NotNull] NinjaVarsParser.DeclareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.sin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSin([NotNull] NinjaVarsParser.SinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.sin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSin([NotNull] NinjaVarsParser.SinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.cos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCos([NotNull] NinjaVarsParser.CosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.cos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCos([NotNull] NinjaVarsParser.CosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.tan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTan([NotNull] NinjaVarsParser.TanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.tan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTan([NotNull] NinjaVarsParser.TanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.asin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsin([NotNull] NinjaVarsParser.AsinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.asin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsin([NotNull] NinjaVarsParser.AsinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.acos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAcos([NotNull] NinjaVarsParser.AcosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.acos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAcos([NotNull] NinjaVarsParser.AcosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.atan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtan([NotNull] NinjaVarsParser.AtanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.atan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtan([NotNull] NinjaVarsParser.AtanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.atan2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtan2([NotNull] NinjaVarsParser.Atan2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.atan2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtan2([NotNull] NinjaVarsParser.Atan2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.myif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMyif([NotNull] NinjaVarsParser.MyifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.myif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMyif([NotNull] NinjaVarsParser.MyifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.myif_short"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMyif_short([NotNull] NinjaVarsParser.Myif_shortContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.myif_short"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMyif_short([NotNull] NinjaVarsParser.Myif_shortContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.mywhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMywhile([NotNull] NinjaVarsParser.MywhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.mywhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMywhile([NotNull] NinjaVarsParser.MywhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.mydo_while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMydo_while([NotNull] NinjaVarsParser.Mydo_whileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.mydo_while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMydo_while([NotNull] NinjaVarsParser.Mydo_whileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.myfor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMyfor([NotNull] NinjaVarsParser.MyforContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.myfor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMyfor([NotNull] NinjaVarsParser.MyforContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaVarsParser.meaningfulType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeaningfulType([NotNull] NinjaVarsParser.MeaningfulTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaVarsParser.meaningfulType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeaningfulType([NotNull] NinjaVarsParser.MeaningfulTypeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
